spring.application.name=parichay

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/parichay_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Initialization (To seed your status table)
spring.sql.init.mode=always

# Default Admin credentials for testing
spring.security.user.name=admin
spring.security.user.password=trust@123
spring.security.user.roles=ADMIN